<div class="check-installation content-header" style=" overflow: hidden; ">
    <?php $version = Mage::getConfig()->getNode()->modules->Netreviews_Avisverifies->version; ?>
    <h2 style="width: 100%;float: left;">
        <?php echo $this->__('Verified Reviews') ?> 
        <small style="font-size:9px;"><?php echo $this->__('version') ?> : <?php echo $version ?></small>
    </h2>
    <table style="width: 350px;float: left;">
        <thead>
            <th width="190"><?php echo $this->__('Table Name') ?>:</th>
            <th><?php echo $this->__('Status') ?></th>
        </thead>
        <tbody>
            <?php $table = $this->getTables(); ?>
            <?php $table = (is_array($table))? $table : array(); ?>
            <?php foreach($table as $nom=>$val): ?>
            <tr>
                <td><?php echo $nom ?></td> 
                <td align="center">
                    <img alt="<?php echo ($val)? "enabled" : "error" ?>" src="<?php echo ($val)? $this->getSkinUrl('images/fam_bullet_success.gif') : $this->getSkinUrl('images/cancel_btn_icon.gif') ?>" />
                </td>
                <td>
                    <?php echo ($val)? "Installed" : "Not-installed" ?>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <div style="float: left; width: 1px;height: 65px; margin: 1px 15px ; border-left: 1px solid #ccc"></div>
    <table style="width: 350px;float: left;">
        <thead>
            <th width="190"><?php echo $this->__('Table Orders Fields') ?>:</th>
            <th><?php echo $this->__('Status') ?></th>
        </thead>
        <tbody>
            <?php $table = $this->getOrders(); ?>
            <?php $table = (is_array($table))? $table : array(); ?>
            <?php foreach($table as $nom=>$val): ?>
            <tr>
                <td><?php echo $nom ?></td> 
                <td align="center">
                    <img alt="<?php echo ($val)? "enabled" : "error" ?>" src="<?php echo ($val)? $this->getSkinUrl('images/fam_bullet_success.gif') : $this->getSkinUrl('images/cancel_btn_icon.gif') ?>" />
                </td>
                <td>
                    <?php echo ($val)? "Installed" : "Not-installed" ?>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <div style="float: left; width: 100%;height: 1px;"></div>
    <table style="width: 350px;float: left;">
        <thead>
            <th width="190"><?php echo $this->__('Table Fields Count') ?>:</th>
            <th><?php echo $this->__('Status') ?></th>
        </thead>
        <tbody>
            <?php $table = $this->getCount(); ?>
            <?php $table = (is_array($table))? $table : array(); ?>
            <?php foreach($table as $nom=>$val): ?>
            <tr>
                <td><?php echo $nom ?></td>
                <td><?php echo $val ?></td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php $checkOrders = $this->getData('checkOrders') ?>
    <?php if(!empty($checkOrders)): ?>
        <?php $header = (isset($checkOrders[0]))? array_keys($checkOrders[0]): array(); ?>
        <h2 style="float: left; width: 100%;"><?php echo $this->__('Check orders Table') ?>:</h2>
        <table style="width: 1250px;float: left;"  border="1">
            <thead>
                <?php foreach($header as $val): ?>
                    <th style="text-align: center;" ><?php echo $val; ?></th>
                <?php endforeach; ?>
            </thead>
            <tbody>
                <?php foreach($checkOrders as $data): ?>
                    <tr>
                        <?php foreach($data as $val): ?>
                            <td align="center" ><?php echo ($val === NULL)? 'NULL' :$val ?></td>
                        <?php endforeach ?>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>

<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Advanced Options') ?></h3></td>
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span><?php echo $this->__('Submit') ?></span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/post')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Install Tables')?></h4>
        <fieldset id="my-fieldset">
            <table cellspacing="1" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Perform a re-installation of the module tables')?></td>
                    <td class="input-ele"><input type="radio" class="input-radio" name="debug[reinstall]" value="yes" /><?php echo $this->__('Yes')?></td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td class="input-ele"><input type="radio" class="input-radio" name="debug[reinstall]" value="no" /><?php echo $this->__('No')?></td>
                </tr>
            </table>
        </fieldset>
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Flag orders to 1')?></h4>
        <fieldset id="my-fieldset">
            <table cellspacing="1" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Flag all orders to 1')?></td>
                    <td class="input-ele"><input type="radio" class="input-radio" name="debug[flag]" value="yes" /><?php echo $this->__('Yes')?></td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td class="input-ele"><input type="radio" class="input-radio" name="debug[flag]" value="no" /><?php echo $this->__('No')?></td>
                </tr>
            </table>
        </fieldset>
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Add missing fields')?></h4>
        <fieldset id="my-fieldset">
            <table cellspacing="1" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Add missing fields')?></td>
                    <td class="input-ele"><input type="radio" class="input-radio" name="debug[fields]" value="yes" /><?php echo $this->__('Yes')?></td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td class="input-ele"><input type="radio" class="input-radio" name="debug[fields]" value="no" /><?php echo $this->__('No')?></td>
                </tr>
            </table>
        </fieldset>
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Fix fields type')?></h4>
        <fieldset id="my-fieldset">
            <table cellspacing="1" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Fix fields type')?></td>
                    <td class="input-ele"><input type="radio" class="input-radio" name="debug[UpdateFields]" value="yes" /><?php echo $this->__('Yes')?></td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td class="input-ele"><input type="radio" class="input-radio" name="debug[UpdateFields]" value="no" /><?php echo $this->__('No')?></td>
                </tr>
            </table>
        </fieldset>
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Check order configuration')?></h4>
        <fieldset id="my-fieldset">
            <table cellspacing="1" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('check order configuration parent child relation')?></td>
                    <td class="input-ele"><input type="text" class="input-text" name="debug[order]" /></td>
                </tr>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>