<?php if($this->getItemCount()): ?>    
<div class="block-related">
	<div class="block-related-internal">
        <h5><?php echo $this->__('Based on your selection, you may be interested in the following items:'); ?></h5>
        <div id="mycarousel" class="related related-slider">
            <div class="slider" >        
            <?php $_i_related = -1; ?>
            <?php foreach($this->getItems() as $_item): $_i_related++; ?>
                <div class="slide <?php if(($this->getItemCount() == 4 && $_i_related == 3) || ($this->getItemCount() == ($_i_related + 1))) echo 'last' ?>">
                    <div class="product">
                        <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(228) ?>" width="228" height="228" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                        <div class="product-details">
                            <div class="button-holder">
                                <a title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" href="<?php echo $this->getAddToCartUrl($_item) ?>"><?php echo $this->__('Add to Cart') ?></a>
                            </div>
                            <?php
                                $_product = $_item; 
                                include('../../product/view/labels.phtml');
                                unset($_product);
                            ?>
                            <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo Mage::helper('core/string')->truncate($this->htmlEscape($_item->getName()), $length = 30, $etc = '...', $remainder = '', $breakWords = true); ?></a></p>
                            <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
            </div>
		</div>
	</div>
</div>
<?php endif ?>