<?php if($this->getCurrencyCount()>1): ?>
    <div class="currency">
    	<div class="currency-menu-title"><?php echo $this->getCurrentCurrencyCode() ?></div>
        <ul class="currency-menu">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <?php if($_code != $this->getCurrentCurrencyCode()): ?>
            	<li class="currency-menu-item">
                	<a href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>" class="currency-code" title="<?php echo $_code ?> - <?php echo $_name ?>"><?php echo $_code ?> - <?php echo $_name ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>