<?php if($this->canShowBlock()): ?>
<div class="inline-layers">
<?php echo $this->getStateHtml() ?>
	<?php if($this->canShowOptions()): ?>
    	<?php $_filters = $this->getFilters() ?>
        	<?php $i=0; foreach ($_filters as $_filter): ?>
            	<?php if($_filter->getItemsCount()): $i++; ?>
                <dl>
                    <dt id="filterlabel<?php echo $i;?>"><?php echo $this->__($_filter->getName()) ?></dt>
                    <dd><?php echo $_filter->getHtml() ?></dd>
                    <script type="text/javascript" >
                            jQuery('#filterlabel<?php echo $i;?>').each(function(){
                                jQuery(this).next().hide();
                                jQuery(this).toggle(function(){
                                    jQuery(this).addClass('active').next().slideDown(200);
                                },function(){
                                    jQuery(this).removeClass('active').next().slideUp(200);
                                })
                            });
                    </script>
                </dl>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
</div>
<?php endif; ?>