<?php if($this->canShowBlock()): ?>
<?php $layer = Mage::getStoreConfig('milanoconfig/product_list/layer'); ?>
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Shopping Options') ?></span></strong>
    </div>
    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if($this->canShowOptions()): ?>
            <dl id="narrow-by-list">
                <?php $_filters = $this->getFilters() ?>
                <?php $i=0; foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount()): $i++; ?>
                    <dt id="filterlabel<?php echo $i;?>"><?php echo $this->__($_filter->getName()) ?></dt>
                    <dd><?php echo $_filter->getHtml() ?></dd>
                    
                    <script type="text/javascript" >   
                        <?php if($layer == 2): ?>     
                            jQuery('#filterlabel<?php echo $i;?>').each(function(){
                                jQuery(this).addClass('active');
                                jQuery(this).toggle(function(){
                                    jQuery(this).removeClass('active').next().slideUp(200);
                                },function(){
                                    jQuery(this).addClass('active').next().slideDown(200);
                                })
                            });                        
                        <?php elseif($layer == 1): ?>     
                            jQuery('#filterlabel<?php echo $i;?>').each(function(){
                                jQuery(this).next().hide();
                                jQuery(this).toggle(function(){
                                    jQuery(this).addClass('active').next().slideDown(200);
                                },function(){
                                    jQuery(this).removeClass('active').next().slideUp(200);
                                })
                            });    
                        <?php endif; ?>                    
                    </script>                     
                <?php endif; ?>
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
