<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
	<div class="box-up-sell-internal">
    <h5 class="upsell-product-h5"><?php echo $this->__('You may also be interested in the following product(s)') ?></h5>
    <table class="mini-products-grid" id="upsell-product-table">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <tr>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <td>
                <?php echo $this->getReviewsSummaryHtml($_link) ?>
                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(171) ?>" width="171" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
                <div class="moreinformation">
                	<?php
							$_product = $_link; 
							include('../view/labels.phtml');
							unset($_product);
					?>
                    <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo Mage::helper('core/string')->truncate($this->htmlEscape($_link->getName()), $length = 25, $etc = '...', $remainder = '', $breakWords = true); ?></a></h3>
                    <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                </div>
            </td>
            <?php else: ?>
            <td class="empty">&nbsp;</td>
            <?php endif; ?>
        <?php endfor; ?>
        </tr>
    <?php endfor; ?>
    </table>
    <script type="text/javascript">decorateTable('upsell-product-table')</script>
    </div>
</div>
<?php endif ?>