<?php // Important: this block is called on the right block area. ?>
<?php $SCRIPTFIXE_ALLOWED = (Mage::getStoreConfig(strtolower('avisverifies/system/SCRIPTFIXE_ALLOWED'))=='yes') ?>
<?php $SCRIPTFIXE_POSITION = (Mage::getStoreConfig(strtolower('avisverifies/system/SCRIPTFIXE_POSITION')) == "right") ?>
<?php if($SCRIPTFIXE_ALLOWED && $SCRIPTFIXE_POSITION): ?>
    <div style="margin: auto;">
        <?php echo Mage::getStoreConfig(strtolower('avisverifies/system/SCRIPTFIXE')) ?>
    </div>
<?php endif;?>