<?php
/**
 * SFC - Featured Catagories Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to support@storefrontconsulting.com so we can send you a copy immediately.
 *
 *
 * @package    SFC_FeaturedCategories
 * @copyright  (C)Copyright 2010 StoreFront Consulting, Inc (http://www.StoreFrontConsulting.com/)
 * @author     Adam Lundrigan
 */
$categories = $this->fastGetFeaturedCategories();
?>
----  static
<div class="bs-featuredCategories">
  <div class="bs-row">
    <!--item 1-->
    <div class="bs-cat bs-blue">
      <a href="#" title="Category Name" class="title">
        <h2>Trio combinabili</h2>
      </a>
      <div class="bs-left">
        <a href="#" title="" style="background-image: url(<?php echo Mage::registry('themeMediaUrl'); ?>ts/bs-blue.png), url(<?php echo Mage::registry('themeMediaUrl'); ?>red/85-category_default.jpg);"></a>
      </div>
      <div class="bs-right">
        <a href="#" title="Category Name"><img src="<?php echo Mage::registry('themeMediaUrl'); ?>red/7714-thickbox_default.jpg" title="" alt="" /></a>
        <a href="#" title="Category Name"><img src="<?php echo Mage::registry('themeMediaUrl'); ?>red/8031-thickbox_default.jpg" title="" alt="" /></a>
      </div>
    </div>
    <!--item 2-->
    <div class="bs-cat bs-red">
      <a href="#" title="Category Name" class="title">
        <h2>ELETRODOMESTICI</h2>
      </a>
      <div class="bs-left">
        <a href="#" title="" style="background-image: url(<?php echo Mage::registry('themeMediaUrl'); ?>ts/bs-red.png), url(<?php echo Mage::registry('themeMediaUrl'); ?>red/10.jpg);"></a>
      </div>
      <div class="bs-right">
        <a href="#" title="Category Name"><img src="<?php echo Mage::registry('themeMediaUrl'); ?>red/7714-thickbox_default.jpg" title="" alt="" /></a>
        <a href="#" title="Category Name"><img src="<?php echo Mage::registry('themeMediaUrl'); ?>red/8031-thickbox_default.jpg" title="" alt="" /></a>
      </div>
    </div>
    <!--item 3-->
    <div class="bs-cat bs-orange">
      <a href="#" title="Category Name" class="title">
        <h2>SCARPINE E ABBIGLIAMENTO NEONATO</h2>
      </a>
      <div class="bs-left">
        <a href="#" title="" style="background-image: url(<?php echo Mage::registry('themeMediaUrl'); ?>ts/bs-orange.png),  url(<?php echo Mage::registry('themeMediaUrl'); ?>red/104.jpg);"></a>
      </div>
      <div class="bs-right">
        <a href="#" title="Category Name"><img src="<?php echo Mage::registry('themeMediaUrl'); ?>red/7714-thickbox_default.jpg" title="" alt="" /></a>
        <a href="#" title="Category Name"><img src="<?php echo Mage::registry('themeMediaUrl'); ?>red/8031-thickbox_default.jpg" title="" alt="" /></a>
      </div>
    </div>
  </div>
  <!--END bs-row-->
</div>
end ----  static
<?php if (sizeof($categories > 0 )) : ?>
<div class="bs-featuredCategories">
  <div class="bs-row">
  <?php 
  $categoryCont = 0;
  foreach ($categories as $categoryId => $productIds) :
  if ($categoryCont++ % 3  == 0 ) : ?>
  </div><div class="bs-row">
  <?php endif;
  $category = Mage::getModel('catalog/category')->load($categoryId);
  ?>
      <div class="bs-cat <?php echo $category->getData('category_color_home'); ?>">
      <a href="<?php echo $category->getUrl(); ?>" title="<?php echo $category->getName(); ?>" class="title">
        <h2><?php echo $category->getName(); ?></h2>
      </a>
      <div class="bs-left">
        <img src="<?php echo Mage::helper('catalog/image')->init($category, 'small_image')->resize(163, 100); ?>" alt="image url: ....">
        <a href="<?php echo $category->getUrl(); ?>" title="<?php echo $category->getName(); ?>" style="background-image: url(<?php echo Mage::registry('themeMediaUrl'); ?>ts/bs-blue.png), url(<?php echo Mage::registry('themeMediaUrl'); ?>red/85-category_default.jpg);"></a>
      </div>
      <?php if (is_array($productIds)) : ?>
      <div class="bs-right">
        <?php foreach ($productIds as $productId) : 
            $product = Mage::getModel('catalog/product')->load($productId); ?>
        <a href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $product->getName(); ?>"><img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image')->resize(163, 100); ?>" title="<?php echo $product->getName(); ?>" alt="<?php echo $product->getName(); ?>" /></a>
        <?php endforeach; ?>
      </div>
      <?php endif; ?>
    </div>
  <?php  endforeach; ?>
  </div>
</div>
<?php endif; ?>



