<?php
/**
 *
 * @category MultiSafepay
 * @package  MultiSafepay_Msp
 * @license  http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /** @var $this MultiSafepay_Msp_Block_Link */ ?>
<a class="msp_checkout_link" href="<?php echo Mage::getUrl("msp/checkout/redirect") ?>">
    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'msp'.DS.'button.png' ?>" style="margin-left: -0px;"/>
</a>

