<?php $product = Mage::registry('product'); ?>
<?php if(is_object($product)): ?>
    <?php $o_av = Mage::getModel('avisverifies/reviews'); ?>
    <?php $o_av->idProduct = $product->getId(); ?>
    <?php $o_av->skuProduct = $product->getSku(); ?>
    <?php $statsProduct = $o_av->getStatsProduct(); ?>
    <?php $countReviews = $statsProduct->getData('nb_reviews'); ?>
    <?php $getNote = $o_av->formatNote($statsProduct->getData('rate')); ?>
    <?php $href = (Mage::getStoreConfig('avisverifies/extra/addReviewToProductPage'))? "javascript:window.avisVerifies.scrollTo()" : $this->getReviewsUrl(TRUE) ?>
    <?php if($countReviews): ?>
        <?php if(!Mage::getStoreConfig('avisverifies/extra/productLightWidget')): ?>
            <div id="av_product_award">
                <div id="top">
                    <div class="ratingWrapper">
                        <div class="ratingInner" style="width:<?php echo ($getNote*20)."%" ?>;"></div>
                    </div>
                    <?php if($countReviews == 1): ?>
                        <b><?php echo $this->__('%d Review', $countReviews) ?></b>
                    <?php else: ?>
                        <b><?php echo $this->__('%d Reviews', $countReviews) ?></b>
                    <?php endif; ?>
                </div>
                <div id="bottom">
                    <a href="<?php echo $href ?>" id="AV_button"><?php echo $this->__('See the review(s)')?></a>
                </div>
                <img id="sceau" src="<?php echo $this->getSkinUrl('images/avisverifies/Sceau_100'.Mage::app()->getLocale()->getLocaleCode().'.png') ?>" />
            </div>
        <?php else : ?>
            <div class="ratings">
                <div class="rating-box">
                    <div class="rating" style="width:<?php echo ($getNote*20)."%" ?>"></div>
                </div>
                <p class="rating-link">
                    <a href="<?php echo $href ?>" id="AV_button">
                        <?php if($countReviews == 1): ?>
                            <?php echo $this->__('%d Review', $countReviews) ?>
                        <?php else: ?>
                            <?php echo $this->__('%d Reviews', $countReviews) ?>
                        <?php endif; ?>
                    </a>
                </p>
            </div>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>