<?php 
    $count_labels = 0;
	
	if (Mage::getStoreConfig('milanoconfig/product_list/new_label') == 1)
	{
        $now = date("Y-m-d H:m:s");   
        $newFromDate = $_product->getNewsFromDate();
        $newToDate = $_product->getNewsToDate();                                               
        if(!(empty($newToDate) && empty($newFromDate)) && ($newFromDate < $now || empty($newFromDate)) && ($newToDate > $now || empty($newToDate))){
            $count_labels++;
			?>
            	<div class="product_label new"><?php echo $this->__('New'); ?></div>
        	<?php
        }
	}

	if (Mage::getStoreConfig('milanoconfig/product_list/sale_label') == 1)
	{
		$specialPrice = number_format($_product->getFinalPrice(), 2);
		$regularPrice = number_format($_product->getPrice(), 2);
		if ($specialPrice != $regularPrice){
            $count_labels++;
	       	?>
            	<div class="product_label sale<?php if($count_labels > 1) echo ' offset'.$count_labels; ?>"><?php echo $this->__('Sale'); ?></div>
        	<?php
		}
	}
    	
	if ($_custom_label = $_product->getData('custom_label'))
	{
       $count_labels++;
	   ?>
            <div class="product_label custom<?php if($count_labels > 1) echo ' offset'.$count_labels; ?>"><?php echo $_custom_label; ?></div>
        <?php
	}
?>