<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
$_show_home_link = Mage::getStoreConfig('milanoconfig/menuoptions/show_home_link') == 1;
$_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
	<div class="nav-container-outer">
	<div class="nav-container">
	<div class="nav-container-inner">
        <ul id="nav"<?php if(!$_show_home_link): ?> class="no-home-link"<?php endif; ?>>
        	<?php if ($_show_home_link): ?><li class="level0 first homelink"><a href="<?php echo $this->getBaseUrl(); ?>"><span><?php echo $this->__('Home') ?></span></a></li><?php 
				endif;
			
			if($_menu) echo $_menu;
				
				$additionalLink = Mage::getStoreConfig('milanoconfig/menuoptions/additional_nav');
            	$additionalLinkUrl = Mage::getStoreConfig('milanoconfig/menuoptions/additional_nav_href');
			
			if ($block1 = $this->getChildHtml('custom_menu_1')): 
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_1')->getTitle(); 
				?>
                <li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
				<?php 
			endif;

            if ($block1 = $this->getChildHtml('custom_menu_2')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_2')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_3')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_3')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_4')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_4')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_5')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_5')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_6')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_6')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_7')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_7')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_8')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_8')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_9')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_9')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_10')):
			    $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_10')->getTitle();
				?>
            	<li class="level0 block_li parent last_block">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;
            
            if($additionalLinkUrl && $additionalLink): ?>
                <li class="level0 custom_link"><a href="<?php echo $additionalLinkUrl ?>" title="<?php echo $additionalLink ?>"><span><?php echo $additionalLink ?></span></a></li>
            <?php endif; ?>
        </ul>
	</div>
    </div>
    </div>
	<div class="mobile-nav-container">
        <?php $_mobileMenu = $this->renderCategoriesMenuHtml(0,'level-top','',true); ?>
        <div id="mobile-menu-button"><?php echo $this->__('Menu') ?></div>
        <ul id="mobile-menu">
            <?php if ($_show_home_link): ?><li class="level0 first homelink"><a href="<?php echo $this->getBaseUrl(); ?>"><span><?php echo $this->__('Home') ?></span></a></li><?php endif; ?>
            <?php 
			
			if($_mobileMenu) echo $_mobileMenu;
				
				$additionalLink = Mage::getStoreConfig('milanoconfig/menuoptions/additional_nav');
            	$additionalLinkUrl = Mage::getStoreConfig('milanoconfig/menuoptions/additional_nav_href');
			
			if ($block1 = $this->getChildHtml('custom_menu_1')): 
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_1')->getTitle(); 
				?>
                <li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
				<?php 
			endif;

            if ($block1 = $this->getChildHtml('custom_menu_2')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_2')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_3')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_3')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_4')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_4')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_5')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_5')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_6')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_6')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_7')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_7')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_8')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_8')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_9')):
                $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_9')->getTitle();
				?>
            	<li class="level0 block_li parent">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;

            if ($block1 = $this->getChildHtml('custom_menu_10')):
			    $block1Title = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('custom_menu_10')->getTitle();
				?>
            	<li class="level0 block_li parent last_block">
                    <a class="level-top"><span><?php echo $block1Title; ?></span></a>
                    <div class="nav_block"><?php echo $block1; ?></div>
                </li>
    			<?php
            endif;
            
            if($additionalLinkUrl && $additionalLink): ?>
                <li class="level0 custom_link"><a href="<?php echo $additionalLinkUrl ?>" title="<?php echo $additionalLink ?>"><span><?php echo $additionalLink ?></span></a></li>
            <?php endif; ?>
        </ul>
	</div>