<?php
        $_product = null;
        $image = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wysiwyg/fblogo-big.jpg';
        $type = 'og:website';
        $custom_meta ='';
        if (
            Mage::app()->getFrontController()->getRequest()->getModuleName() == 'catalog' &&
            Mage::app()->getFrontController()->getRequest()->getControllerName() == 'product'
        ) {
            $params = Mage::app()->getFrontController()->getRequest()->getParams();
            $_product = Mage::getModel('catalog/product')->load($params['id']);
            $image =  Mage::helper('catalog/image')->init($_product, 'small_image')->resize(858, 446);
            $price = number_format($_product->getPrice(),2);
            $type = 'og:product';
            $custom_meta =<<<EOT
    <meta property="product:price:amount"      content="{$price}"/>
    <meta property="product:price:currency"    content="EUR"/>
EOT;
        }
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<meta property="og:locale" content="it_IT">
<link rel="canonical" href="<?php echo Mage::getBaseUrl();?>">
<meta property="og:url" content="<?php echo Mage::helper('core/url')->getCurrentUrl();?>"/>
<meta property="og:title" content="<?php echo $this->getTitle() ?>" />
<meta property="og:site_name" content="<?php echo Mage::app()->getStore()->getName();?>" />
<meta property="og:description" content="<?php echo htmlspecialchars($this->getDescription()) ?>">
<meta property="og:image" content="<?php echo $image; ?>">
<meta property="og:image:type" content="image/jpeg">
<meta property="og:image:width" content="858">
<meta property="og:image:height" content="446">
<meta property="og:type" content="<?php echo $type; ?>" />
<?php echo $custom_meta; ?>

<link rel="author" href="https://plus.google.com/113160380943238250605" />



<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php // echo $this->helper('core/js')->getTranslatorScript() // ROMARS EDITED ?> 
<?php echo $this->getIncludes() ?>

<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
