<div id="top"></div>
<div class="header-container">
	<div class="header-small-container">
        <div class="header">
            <div class="header-left">
            	<div class="bs-topSearch"><?php echo $this->getChildHtml('topSearch') ?> 
                	<a class="brandLink" rel="nofollow" href="<?php echo $this->getUrl('marche')?>"  >Cerca tra le nostre <strong>marche</strong> </a>
                </div>  <?php /*?>ROMARS<?php */?>
                <?php echo $this->getChildHtml('store_switcher') ?>
                <?php echo $this->getChildHtml('store_language') ?>
				<?php echo $this->getChildHtml('currency') ?>
                <div class="cms-header-links"><?php echo $this->getChildHtml('cms_header_links') ?></div>
            </div>
            <div class="header-right">
                <span class="welcome-msg"><?php echo $this->getWelcome() ?></span>
            </div>      
        </div>
    </div>
    <div class="header-main-container">
    	<div class="header">
            <div class="header-left header-logo ">
            	<?php if ($this->getIsHomePage()):?>
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><h1><strong><?php echo Mage::getStoreConfig('general/store_information/name') ?></strong></h1><img src="<?php echo Mage::registry('themeMediaUrl').Mage::getStoreConfig('milanoconfig/generaloptions/logo'); ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
                <?php else:?>
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><h2><strong><?php echo Mage::getStoreConfig('general/store_information/name') ?></strong></h2><img src="<?php echo Mage::registry('themeMediaUrl').Mage::getStoreConfig('milanoconfig/generaloptions/logo'); ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
                <?php endif?>
            </div>
            <div class="header-center header-menu">
								<?php echo $this->getChildHtml('header_menu') ?>
	
            </div>
            <div class="header-right">
                <?php echo $this->getChildHtml('topLinks') ?> 
                <?php echo $this->getChildHtml('top_cart') ?> <?php /*?>ROMARS<?php */?>

                 
            </div>
            <div class="header-contactNr">
            	<div class="infoDiv infornr"></div>
                <div class="infoDiv infoSkype">
<?php if (strpos(Mage::helper('core/url')->getCurrentUrl(),'/checkout/') == false) : ?>
<!-- Google Code per il tag di remarketing -->
<!--------------------------------------------------
I tag di remarketing possono non essere associati a informazioni di identificazione personale o inseriti in pagine relative a categorie sensibili. Ulteriori informazioni e istruzioni su come impostare il tag sono disponibili alla pagina: http://google.com/ads/remarketingsetup
--------------------------------------------------->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1005441481;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/1005441481/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>       
<?php endif;?>
<div id="SkypeButton_Call_storebaby_italia_1">
  <script type="text/javascript">
    Skype.ui({
      "name": "chat",
      "element": "SkypeButton_Call_storebaby_italia_1",
      "participants": ["storebaby_italia"],
      "imageSize": 14
    });
  </script>
</div>
                </div>
                <div class="infoDiv infoWhatsup"></div>
            
            </div>    
        </div>
    </div>
    <?php echo $this->getChildHtml('topMenu'); ?>
    <div class="header-promo-container">
    	<div class="header">
			<?php echo $this->getChildHtml('header_promo') ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('topBread'); ?>
    <?php echo $this->getChildHtml('topContainer'); ?>
</div>